In [53]:
import numpy as np

In [63]:
arr=np.array([[1,2],[1,2]])
arr2=np.array([[1,2],[1,2]])

In [55]:
arr.sum()

20

In [56]:
print(arr+arr2)

[[2 4 6 8]
 [2 4 6 8]]


In [57]:
two_d = []

for i in range(len(arr)):
    one_d = [] 
    for j in range(len(arr[i])):
        a = arr[i][j] + arr2[i][j]  
        one_d.append(a)
    two_d.append(one_d)

In [52]:
print(two_d)

[[2, 4, 6, 8], [2, 4, 6, 8]]


In [58]:
two_d = []

for i in range(len(arr)):
    one_d = [] 
    for j in range(len(arr[i])):
        a = arr[i][j] * arr2[i][j]  
        one_d.append(a)
    two_d.append(one_d)

In [59]:
print(two_d)

[[1, 4, 9, 16], [1, 4, 9, 16]]


In [64]:
np.matmul(arr,arr2)

array([[3, 6],
       [3, 6]])

In [106]:
arr=np.array([[1,2],[1,2]])
arr2=np.array([[1,2],[1,2]])


In [117]:
two_d=[]
for i in range(len(arr)):
    one_d=[]
    for j in range(len(arr2[0])):
        sum=0
        for k in range(len(arr[i])):
            sum =sum+ arr[i][k] * arr2[k][j]
            print(arr[i][k],'------------',arr2[k][j])
            print('-------',sum,'-------')
        one_d.append(sum)
        print('------',one_d,'------')
        
    two_d.append(one_d)

1 ------------ 1
------- 1 -------
2 ------------ 1
------- 3 -------
------ [3] ------
1 ------------ 2
------- 2 -------
2 ------------ 2
------- 6 -------
------ [3, 6] ------
1 ------------ 1
------- 1 -------
2 ------------ 1
------- 3 -------
------ [3] ------
1 ------------ 2
------- 2 -------
2 ------------ 2
------- 6 -------
------ [3, 6] ------


In [111]:
print(two_d)

[[3, 6], [3, 6]]
