Imports

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

def displayImg(title,img):
    cv2.imshow(title,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Task#1: Find Boundaries from the Image

In [2]:
img = cv2.imread('task1.png',cv2.IMREAD_GRAYSCALE)
_,binary_image = cv2.threshold(img,128,255,cv2.THRESH_BINARY)

displayImg('Original Image',img)
displayImg('Binarized Image',binary_image)

# kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
kernel = np.array(
    [
        [1,1,1,1,1],
     [1,1,1,1,1],
      [1,1,1,1,1],
       [1,1,1,1,1],
        [1,1,1,1,1]
    ]
)
print(kernel)

closedImg = cv2.morphologyEx(binary_image, cv2.MORPH_CLOSE, kernel)
displayImg('Closed Image',closedImg)
    

erodedImg = cv2.erode(closedImg, kernel)
displayImg('Eroded Image',erodedImg)

    
boundary_img = cv2.subtract(closedImg, erodedImg)
displayImg('Boundary Image',boundary_img)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Task#2: Use opening operator to seperate horizontal and vertical lines

In [3]:
linesImg = cv2.imread('lines.png',cv2.IMREAD_GRAYSCALE)

# We binarize but over here image is already black and white
# _,binary_image = cv2.threshold(linesImg,128,255,cv2.THRESH_BINARY)

# Failed: Not Good Output
# horizontalKernel = cv2.getStructuringElement(cv2.MORPH_RECT,(7,3))
# verticalKernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,7))

# Failed Not Good Output
# horizontalKernel = cv2.getStructuringElement(cv2.MORPH_RECT,(9,3))
# verticalKernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,9))

horizontalKernel = np.ones((3,11), dtype=np.uint8)
verticalKernel = np.ones((11, 3), dtype=np.uint8)

# horizontalKernel = cv2.getStructuringElement(cv2.MORPH_RECT,(11,3))
# verticalKernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3,11))


horizontalLines = cv2.morphologyEx(linesImg,cv2.MORPH_OPEN,horizontalKernel)
verticalLines = cv2.morphologyEx(linesImg,cv2.MORPH_OPEN,verticalKernel)

displayImg('Original Image',linesImg)
displayImg('Horizontal Lines',horizontalLines)
displayImg('Vertical Lines',verticalLines)



Task#3: 

In [4]:

img = cv2.imread('task3.png', cv2.IMREAD_GRAYSCALE)
displayImg('Original Image',img)

_, binary_image = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY_INV)
displayImg('Binarized Image',binary_image)


binary_image = cv2.bitwise_not(binary_image)

kernel_line = np.ones((1, 50), np.uint8)
dilated_image_lines = cv2.dilate(binary_image, kernel_line, iterations=1)
displayImg('Dilated Image Lines',dilated_image_lines)
num_labels_lines, labels_lines = cv2.connectedComponents(dilated_image_lines)
num_lines = num_labels_lines - 1  

kernel_word = np.ones((1, 8), np.uint8)
dilated_image_words = cv2.dilate(binary_image, kernel_word, iterations=1)
displayImg('Dilated Image Words',dilated_image_words)
num_labels_words, labels_words = cv2.connectedComponents(dilated_image_words)
num_words = num_labels_words - 1  

print(f"Number of lines: {num_lines}")
print(f"Number of words: {num_words}")


Number of lines: 6
Number of words: 13


Task#4: Make a bounding box around text inside an image

In [5]:
img = cv2.imread('task4.png',cv2.IMREAD_GRAYSCALE)
displayImg('Original Image',img)

_, binary_image = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY_INV)
displayImg('Binarized Image',binary_image)

kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))  
dilated = cv2.dilate(binary_image, kernel, iterations=1)          

contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

for contour in contours:
    x, y, w, h = cv2.boundingRect(contour)
    if w > 10 and h > 10: 
        cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

displayImg("Bounding Boxes",img=img)
